language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t musthafakdml/frontend -f frontend/Dockerfile.dev frontend

script:
    - docker run -e CI=true musthafakdml/frontend npm run test -- --coverage